using BApp.Domain.Enums;

namespace BApp.Domain.Models
{
    public class UserColor
    {
        //composed primary key(UserId + ColorHexValue)
        //and/or autogenerated primary key(Id)
        //a color value (RGB/Tint/Shade/HSL/HSV can be computed based on the hex - computations in ColorExtenssion class)
        public int Id { get; set; }

        public int UserId { get; set; }

        public string ColorHexValue { get; set; }

        public DifficultyStatus Difficulty { get; set; }

        public DateTime SavingDate { get; set; }

        public User User { get; set; }
    }
}
